language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: ruYdmEHFIo1fiqDyUWLpoznc9mbofW2yPC34jmLN97ZXreC1Qito5VaYMTV1j/w5qmRcWjENQtgSJ5hYT8+kxhlUbIpUGdg+LqK3sh7ca2SP4O73v46HVwkiAAqgMOE45G04hodbTrPIDErE5R1+dbUo85VJdBynuXd1+2y1n0YdaYVUSrfmsRIiOxwW4E6HlwEgsDnj5fxKvNbMhBmcSaELtCMcppeoIBVj9YucE1eDvvZ4ceuQc2RDCgVQ+k2ULo2wYQKtxQYm4Ynpy9btGUxuUSUn+NYqQmju1ZtxIwQ0zJ1T6N2n7a4y/yK2+FC08Qnc4DLUILWUY6qLkup8ayg3cl12NCriz1rTNcbfJxygonCMdO2IVzr4kgYZywfeB5P34BFeoQOMRFM2yYyYPYfSlum38Mt9BTHGGW0nx9XgXT8CR3NaQKPF3O/pufBTSslYiHXxSXXTInc2iGcYXymWr2MNkJGtIc16qJPdM1xcwFPgSz4YX0riDAcNAoDkz/MSBuo83izPln2URsCG60/hdJSs7ryi7xZVJbth7z7JY/5O1h91VTdtK/E/zuokAy3CapoVF0R4GDgsfd21NtqGl3I9mL1FpSFR4s7rpZTQS3lhVtiV137alyHOcMbCCnu+eYt7fhg4bJpdId+P0cImvjSkKCtCqsUfcnEQW6U=
  on:
    tags: true
    repo: mike12523/slippy
    python: 3.8
