language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: mike12523
  password:
    secure: EG6Ihp45Kwu402cqDsQE0FXc7MOD7U3JrIZVYEKGfYRgJ9EfRFzguqAvikjoBgxBXorOnXIWD9WTc7sY92K3QDxLMgMtY/PPL03GeFdy2kV8u2SxPc4Zo+45uoRrxKHI9AdxR2IeUiUfyI5QAqOaixFDueR9RqieWfbnCGDcBYznsn6S8aJTb9Am7lPQpCXJmwWx6Z18N7K3bThxqo3FL02AEbei1Zvcy72WWNpV+52zWlLp38P1gQAkBZQYmcWdeMmaechiAwBtChM4nMSE2Kl9A+JAo59MhBfPSRdD6dxmpXPTSJFc8385HrT7QmjN9zfpxGGZB1lmMblWxSmhZ8s6dU9vLcb7vJcEaNZmO8rcmHybYYG0hvNbA7Z7MA5CmLkChc2meWBuSFuNxnfaUmqmjWinljpbTb+uhoICOIcp7MzXRD3l9XZlaEM1rBx5imi1mLVwfLVxuSxQarL/a9KSxpxYlUTV1t4OmiQz9Zz53F75H0eyVrm2/Nn3/83e2WsqerQvW/52RkCvcm4vHPbiwLehDGdljJB84tlgmTvZZqt4o74KfvZ/2pEorXsjryAngDJOM1dEebYAM44dPpNW73/7hOLefrWGYjg3iBYYWgwX/GkDtl3+75b9I0K/VYk9Zi695JtQNCsAWZRna8yJAsEXm9a+TrGXaVV/fN0=
  on:
    tags: true
    repo: mike12523/slippy
    python: 3.8
